# Generated by Django 5.0.6 on 2024-05-12 07:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0002_remove_schoolstudentsmodel_gender'),
        ('student', '0006_alter_state_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('phoneNo', models.BigIntegerField()),
                ('profile', models.ImageField(upload_to='teacherProfile')),
                ('address', models.TextField()),
                ('role', models.CharField(max_length=100)),
                ('teachOfClass', models.CharField(max_length=20)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacherCity', to='student.city')),
                ('schoolName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacherSchool', to='school.schoolprofilemodel')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacherState', to='student.state')),
                ('totalOfStudent', models.ManyToManyField(blank=True, null=True, to='student.studentprofilemodel')),
            ],
        ),
    ]
