# Generated by Django 5.0.6 on 2024-05-18 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_teacherprofilemodel_teacherverifybyschool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherprofilemodel',
            name='teacherVerifyBySchool',
            field=models.CharField(choices=[('Verify', 'Verify'), ('NotVerify', 'NotVerify')], default=False, max_length=20),
        ),
    ]
