# Generated by Django 5.0.6 on 2024-05-18 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0005_alter_teacherprofilemodel_teacherverifybyschool'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofilemodel',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacherprofilemodel',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='teacherprofilemodel',
            name='teacherVerifyBySchool',
            field=models.CharField(choices=[('Verify', 'Verify'), ('NotVerify', 'NotVerify')], default='NotVerify', max_length=20),
        ),
    ]
