# Generated by Django 5.0.6 on 2024-05-22 08:52

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0015_remove_schoolteacherverification_teacherverifybyschool'),
        ('teacher', '0005_alter_teacherprofilemodel_teacherverifybyschool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherprofilemodel',
            name='teacherVerifyBySchool',
            field=models.CharField(choices=[('Verify', 'Verify'), ('NotVerify', 'NotVerify')], default='NotVerify', max_length=20),
        ),
        migrations.CreateModel(
            name='TeacherAttendanceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacherAttend', models.CharField(choices=[('Present', 'Present'), ('Absence', 'Absence')], default='Absence', max_length=10)),
                ('date', models.DateTimeField(default=datetime.datetime(2024, 5, 22, 8, 52, 22, 618408, tzinfo=datetime.timezone.utc))),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('schoolName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.schoolprofilemodel')),
                ('teacherName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.teacherprofilemodel')),
            ],
        ),
    ]
