# Generated by Django 5.0.6 on 2024-05-18 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0006_teacherprofilemodel_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherprofilemodel',
            name='created',
        ),
        migrations.RemoveField(
            model_name='teacherprofilemodel',
            name='updated',
        ),
    ]
