# Generated by Django 5.0.6 on 2024-05-11 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolprofile',
            name='studentList',
            field=models.ManyToManyField(blank=True, null=True, to='student.studentprofile'),
        ),
    ]
