# Generated by Django 5.0.6 on 2024-05-12 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_remove_schoolstudentsmodel_gender'),
        ('teacher', '0002_alter_teacherprofilemodel_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolstudentsmodel',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='schoolsTeacher', to='teacher.teacherprofilemodel'),
            preserve_default=False,
        ),
    ]
