# Generated by Django 5.0.6 on 2024-05-11 05:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_alter_schoolprofile_authadmin_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolprofile',
            name='authAdmin',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='authAdminSPM', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorSProfile', to=settings.AUTH_USER_MODEL),
        ),
    ]
