# Generated by Django 5.0.6 on 2024-05-12 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_schoolstudentsmodel_teacher'),
        ('teacher', '0002_alter_teacherprofilemodel_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolstudentsmodel',
            name='teacher',
        ),
        migrations.AddField(
            model_name='schoolstudentsmodel',
            name='teacher',
            field=models.ManyToManyField(null=True, to='teacher.teacherprofilemodel'),
        ),
    ]
