# Generated by Django 5.0.6 on 2024-05-12 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_remove_schoolstudentsmodel_teacher_and_more'),
        ('teacher', '0002_alter_teacherprofilemodel_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolstudentsmodel',
            name='teacher',
            field=models.ManyToManyField(null=True, related_name='teacherSchool', to='teacher.teacherprofilemodel'),
        ),
    ]
