# Generated by Django 5.0.6 on 2024-05-12 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_alter_schoolstudentsmodel_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolstudentsmodel',
            name='teacher',
        ),
    ]
