# Generated by Django 5.0.6 on 2024-05-11 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_rename_author_schoolstudent_schools'),
        ('student', '0003_alter_studentprofile_authadmin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolstudent',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='student.studentprofile'),
        ),
    ]
