# Generated by Django 5.0.6 on 2024-05-12 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_remove_schoolstudentsmodel_teacher'),
        ('teacher', '0002_alter_teacherprofilemodel_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolprofilemodel',
            name='teacher',
            field=models.ManyToManyField(null=True, related_name='teacherSchool', to='teacher.teacherprofilemodel'),
        ),
    ]
