# Generated by Django 5.0.6 on 2024-05-11 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_alter_schoolstudent_student'),
        ('student', '0005_alter_studentprofile_totalfamilymember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolstudent',
            name='schools',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school.schoolprofile'),
        ),
        migrations.AlterField(
            model_name='schoolstudent',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='student.studentprofile'),
        ),
    ]
