# Generated by Django 5.0.6 on 2024-05-11 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_alter_schoolstudent_schools_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolstudent',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schoolstudent',
            name='phoneNo',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='schoolstudent',
            name='schools',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='studentSchools', to='school.schoolprofile'),
        ),
    ]
