# Generated by Django 5.0.6 on 2024-05-14 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0010_schoolnotifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolstudentsmodel',
            name='schoolbystudentVerify',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
