# Generated by Django 5.0.6 on 2024-05-14 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0012_schoolstudentsmodel_author'),
        ('student', '0015_remove_studentprofilemodel_schoolbystudentverify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolstudentsmodel',
            name='schoolProf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='studentSchools', to='school.schoolprofilemodel'),
        ),
        migrations.AlterField(
            model_name='schoolstudentsmodel',
            name='studentProf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='studentsSS', to='student.studentprofilemodel'),
        ),
    ]
