# Generated by Django 5.0.6 on 2024-05-16 05:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0013_alter_schoolstudentsmodel_schoolprof_and_more'),
        ('teacher', '0003_teacherprofilemodel_salary'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolTeacherVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacherName', models.CharField(max_length=100)),
                ('teacherVerifyBySchool', models.BooleanField(default=False, max_length=20)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='published', max_length=10)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('schoolProf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.schoolprofilemodel')),
                ('teacherProf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.teacherprofilemodel')),
            ],
        ),
    ]
