# Generated by Django 5.0.6 on 2024-05-11 05:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phoneNo', models.BigIntegerField()),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('pinCode', models.IntegerField()),
                ('dob', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=30)),
                ('profile', models.ImageField(blank=True, null=True, upload_to='studentImage')),
                ('category', models.CharField(choices=[('General', 'General'), ('SC', 'SC'), ('ST', 'ST'), ('OBC', 'OBC'), ('Others', 'Others')], max_length=30)),
                ('fatherName', models.CharField(blank=True, max_length=50, null=True)),
                ('motherName', models.CharField(blank=True, max_length=50, null=True)),
                ('totalFamilyIncome', models.PositiveIntegerField(blank=True, null=True)),
                ('totalFamilyMember', models.IntegerField()),
                ('status', models.CharField(blank=True, choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10, null=True)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('authAdmin', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='StudentAdmin', to=settings.AUTH_USER_MODEL)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='StudentUsers', to=settings.AUTH_USER_MODEL)),
                ('schoolName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studentschols', to='school.schoolprofile')),
            ],
        ),
    ]
