# Generated by Django 5.0.6 on 2024-05-10 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
        ('student', '0002_alter_studentprofile_schoolname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='schoolName',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='studentschols', to='school.schoolprofile'),
            preserve_default=False,
        ),
    ]
