# Generated by Django 5.0.6 on 2024-05-12 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_studentprofilemodel_schoolname'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofilemodel',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='StuCity', to='student.city'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentprofilemodel',
            name='state',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='StuState', to='student.state'),
            preserve_default=False,
        ),
    ]
