# Generated by Django 5.0.6 on 2024-05-11 05:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_studentprofile_authadmin_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='authAdmin',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='StudentAdmin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='StudentUsers', to=settings.AUTH_USER_MODEL),
        ),
    ]
