# Generated by Django 5.0.6 on 2024-05-11 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_alter_studentprofile_authadmin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='pinCode',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
