# Generated by Django 5.0.6 on 2024-05-12 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_studentprofilemodel_city_studentprofilemodel_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofilemodel',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='StuCity', to='student.city'),
        ),
        migrations.AlterField(
            model_name='studentprofilemodel',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='StuState', to='student.state'),
        ),
    ]
