# Generated by Django 5.0.6 on 2024-05-11 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_alter_studentprofile_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='totalFamilyMember',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
