# Generated by Django 5.0.6 on 2024-05-12 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_rename_city_studentprofilemodel_stucity_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='state',
            options={'verbose_name_plural': 'Student-State'},
        ),
    ]
