# Generated by Django 5.0.6 on 2024-05-12 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_studentattendance_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentattendance',
            name='name',
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='studentName',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='student.studentprofilemodel'),
            preserve_default=False,
        ),
    ]
