# Generated by Django 5.0.6 on 2024-05-14 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0014_studentprofilemodel_schoolbystudentverify'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofilemodel',
            name='schoolbystudentVerify',
        ),
    ]
