# Generated by Django 5.0.6 on 2024-05-20 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0015_remove_studentprofilemodel_schoolbystudentverify'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentattendance',
            old_name='publish',
            new_name='date',
        ),
    ]
