# Generated by Django 5.0.6 on 2024-05-10 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0002_alter_user_phoneno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='types',
            field=models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('staff', 'staff'), ('school', 'school'), ('admin', 'admin')], default='admin', max_length=50),
        ),
    ]
