# Generated by Django 5.0.6 on 2024-05-10 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0003_alter_user_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='city',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phoneNo',
        ),
        migrations.RemoveField(
            model_name='user',
            name='state',
        ),
        migrations.RemoveField(
            model_name='user',
            name='status',
        ),
    ]
